### ISSUE TITLE
Not able to view html output when link html files or respective engines 

### ISSUE THREAD

**Issue by HaarisIqubal** [gjuoun/view-engine#2]
I tried to use ejs and handlebars but won’t able to get any output on webpage

I am using deno command 
deno run —allow-net app.ts 

Should i also type 
—allow-read and —allow-write flag.

**Comment by gjuoun** [comment]
Can I see your code?

**Comment by HaarisIqubal** [comment]
My code is similar which is written in guide page of the extension i just simply copy and paste it.

**Comment by kokpheng** [comment]
Please change this line to code in app.ts because it points to wrong path of index.html file.
```
ctx.render("./view/index.html", { data: { name: "John" } });
```
to 
```
ctx.render("index.html", { data: { name: "John" } });
```

**Comment by gjuoun** [comment]
> My code is similar which is written in guide page of the extension i just simply copy and paste it.

Suppose your folder like this
```
./
|-index.html
|-app.ts
```

With these two files
* index.html
```html
<--index.html-->
<body>
  <h1>{{data.name}}</h1>
</body>
```

* app.ts
```ts
// app.ts
import { Application } from "https://deno.land/x/oak/mod.ts";
import {
  viewEngine,
  engineFactory,
  adapterFactory,
} from "https://deno.land/x/view_engine/mod.ts";

const denjuckEngine = await engineFactory.getDenjuckEngine();
const oakAdapter = await adapterFactory.getOakAdapter();

const app = new Application();

app.use(viewEngine(oakAdapter, denjuckEngine));

app.use(async (ctx, next) => {
  ctx.render("index.html", { data: { name: "John" } });
});

await app.listen({ port: 8000 });
```

This worked for me, give it a try

**Comment by gjuoun** [comment]
> Please change this line to code in app.ts because it points to wrong path of index.html file.
> 
> ```
> ctx.render("./view/index.html", { data: { name: "John" } });
> ```
> 
> to
> 
> ```
> ctx.render("index.html", { data: { name: "John" } });
> ```

My bad, the ```/src``` folder is for development purposes. I should gitignore that.

**Comment by HaarisIqubal** [comment]
Thanks a lot finally this code work and i really excited to see the future of deno and your module should make difference.

I am making a youtube video featuring your engine hope you may like it... [recoding](https://www.youtube.com/channel/UCnhsNyu4bdDxuW1TT3hg-pg)

**Comment by gjuoun** [comment]
@HaarisIqubal Thanks for promoting the module. Good job on your videos!
